{
  psql.pas — every PSQL module type, driven from Pascal.

  The fbintf twin of ../cpp/psql.cpp, building the document's worked
  examples on a scratch database:
    - an executable procedure (hire) with INSERT ... RETURNING into an
      output parameter, called via EXECUTE PROCEDURE — fbintf returns the
      one output message as IResults from IStatement.Execute, no cursor;
    - a BEFORE INSERT trigger writing an audit row per hire;
    - a selectable procedure (raises) streaming SUSPENDed rows, fetched
      like a table with SELECT ... FROM raises(10) through IResultSet;
    - a custom PSQL exception, caught client-side as EIBInterBaseError —
      its Message carries the same IUtil::formatStatus rendering the C++
      twin prints, including the PSQL stack trace with the procedure name
      and line/column.

  Idempotent — safe to re-run.  See ../../psql-and-stored-procedures.md.

  Build & run (see ../README.md):
      make -C samples/fpc bin/psql && samples/fpc/bin/psql
}
program psql;

{$mode delphi}
{$codepage UTF8}
{$interfaces COM}

uses SysUtils, IB, FBHandsOn;

const Calls: array[0..1] of AnsiString = (
  'EXECUTE PROCEDURE hire(''Ada'', 5000)',
  'EXECUTE PROCEDURE hire(''Grace'', 6000)');

var A: IAttachment;
    Tr: ITransaction;
    Stmt: IStatement;
    Res: IResults;
    R: IResultSet;
    i: integer;

begin
  A := AttachOrCreate(DbConn('psql'));
  Tr := A.StartTransaction([isc_tpb_write, isc_tpb_nowait,
    isc_tpb_read_committed, isc_tpb_rec_version], taCommit);

  { -- Schema: the document's worked examples, made idempotent. ----------
    On re-runs the procedures still reference emp; reduce them to stubs
    first so RECREATE TABLE is not blocked by dependencies. }
  A.ExecImmediate(Tr, 'CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30),' +
    ' p_salary NUMERIC(10,2)) RETURNS (new_id INTEGER) AS BEGIN END');
  A.ExecImmediate(Tr, 'CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))' +
    ' RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))' +
    ' AS BEGIN END');
  Tr.CommitRetaining;
  A.ExecImmediate(Tr, 'RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS' +
    ' IDENTITY PRIMARY KEY, name VARCHAR(30), salary NUMERIC(10,2))');
  A.ExecImmediate(Tr, 'RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))');
  A.ExecImmediate(Tr, 'CREATE OR ALTER EXCEPTION low_salary ''salary below minimum''');
  Tr.CommitRetaining;

  A.ExecImmediate(Tr,
    'CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))'#10 +
    'RETURNS (new_id INTEGER) AS'#10 +
    'BEGIN'#10 +
    '  IF (p_salary < 1000) THEN EXCEPTION low_salary;'#10 +
    '  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)'#10 +
    '    RETURNING id INTO :new_id;'#10 +
    'END');
  A.ExecImmediate(Tr,
    'CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS'#10 +
    'BEGIN'#10 +
    '  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,'#10 +
    '    ''insert emp '' || COALESCE(NEW.name, ''?''));'#10 +
    'END');
  A.ExecImmediate(Tr,
    'CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))'#10 +
    'RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS'#10 +
    'BEGIN'#10 +
    '  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO'#10 +
    '  BEGIN'#10 +
    '    new_salary = new_salary * (1 + pct / 100);'#10 +
    '    SUSPEND;'#10 +                       { yield one row to the caller }
    '  END'#10 +
    'END');
  Tr.CommitRetaining;

  { -- 1. Executable procedure: one output message, no cursor. ----------- }
  for i := low(Calls) to high(Calls) do
  begin
    Stmt := A.Prepare(Tr, Calls[i]);
    Res := Stmt.Execute;
    writeln(Format('%-42s -> NEW_ID = %d',
      [Calls[i], Res.ByName('NEW_ID').AsInteger]));
  end;

  { -- 2. The trigger fired once per insert. ----------------------------- }
  writeln('audit_log rows (trigger emp_bi):              ',
    A.OpenCursorAtStart(Tr, 'SELECT COUNT(*) FROM audit_log')[0].AsInteger);

  { -- 3. Selectable procedure: SUSPEND streams rows into a cursor. ------ }
  writeln;
  writeln('SELECT * FROM raises(10):');
  R := A.OpenCursor(Tr,
    'SELECT id, name, new_salary FROM raises(10) ORDER BY id');
  writeln(Format('  %-4s %-8s %10s', ['ID', 'NAME', 'NEW_SALARY']));
  while R.FetchNext do
    writeln(Format('  %-4d %-8s %10.2f',
      [R[0].AsInteger, R[1].AsString, R[2].AsCurrency]));

  { -- 4. The custom exception, with its PSQL stack trace.  fbintf uses
    the prepared path throughout, so nothing is swallowed: the full
    status vector arrives in EIBInterBaseError. ------------------------- }
  writeln;
  writeln('EXECUTE PROCEDURE hire(''Poorpay'', 500) ->');
  try
    Stmt := A.Prepare(Tr, 'EXECUTE PROCEDURE hire(''Poorpay'', 500)');
    Stmt.Execute;
    writeln('BUG: the low_salary exception did not surface');
  except
    on E: EIBInterBaseError do
      writeln('gds ', E.IBErrorCode, ': ', E.Message);
  end;

  Tr.Commit;
  writeln('done.');
end.
