/*
 *  psql.cpp — companion to ../../psql-and-stored-procedures.md
 *
 *  Builds the document's worked examples on a scratch database and drives
 *  every module type from the client:
 *    - an executable procedure (hire) with INSERT ... RETURNING into an
 *      output parameter, called via EXECUTE PROCEDURE (output message read
 *      directly — executable procedures return one row, not a cursor);
 *    - a BEFORE INSERT trigger writing an audit row per hire;
 *    - a selectable procedure (raises) streaming SUSPENDed rows, fetched
 *      like a table with SELECT ... FROM raises(10);
 *    - a custom PSQL exception, caught client-side and rendered with
 *      IUtil::formatStatus — including the PSQL stack trace with the
 *      procedure name and line/column.
 *
 *  Idempotent — safe to re-run.
 */

#include "fb_sample.h"

using namespace Firebird;
using fbsample::master;

int main(int argc, char** argv)
{
	const char* database = fbsample::argOrDefault(argc, argv, 1,
		"inet://localhost//tmp/fbhandson/psql.fdb");

	try
	{
		fbsample::Db db;
		db.attachOrCreate(database);
		ITransaction* tra = db.start();

		// -- Schema: the document's worked examples, made idempotent. ------
		// On re-runs the procedures still reference emp; reduce them to
		// stubs first so RECREATE TABLE is not blocked by dependencies.
		db.exec(tra, "CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30),"
			" p_salary NUMERIC(10,2)) RETURNS (new_id INTEGER) AS BEGIN END");
		db.exec(tra, "CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))"
			" RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))"
			" AS BEGIN END");
		tra->commitRetaining(&db.status);
		db.exec(tra, "RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS"
			" IDENTITY PRIMARY KEY, name VARCHAR(30), salary NUMERIC(10,2))");
		db.exec(tra, "RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))");
		db.exec(tra, "CREATE OR ALTER EXCEPTION low_salary 'salary below minimum'");
		tra->commitRetaining(&db.status);

		db.exec(tra,
			"CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))\n"
			"RETURNS (new_id INTEGER) AS\n"
			"BEGIN\n"
			"  IF (p_salary < 1000) THEN EXCEPTION low_salary;\n"
			"  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)\n"
			"    RETURNING id INTO :new_id;\n"
			"END");
		db.exec(tra,
			"CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS\n"
			"BEGIN\n"
			"  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,\n"
			"    'insert emp ' || COALESCE(NEW.name, '?'));\n"
			"END");
		db.exec(tra,
			"CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))\n"
			"RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS\n"
			"BEGIN\n"
			"  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO\n"
			"  BEGIN\n"
			"    new_salary = new_salary * (1 + pct / 100);\n"
			"    SUSPEND;\n"                       // yield one row to the caller
			"  END\n"
			"END");
		tra->commitRetaining(&db.status);

		// -- 1. Executable procedure: one output message, no cursor. -------
		for (const char* call : { "EXECUTE PROCEDURE hire('Ada', 5000)",
		                          "EXECUTE PROCEDURE hire('Grace', 6000)" })
		{
			IStatement* stmt = db.att->prepare(&db.status, tra, 0, call,
				SQL_DIALECT_V6, IStatement::PREPARE_PREFETCH_METADATA);
			IMessageMetadata* out = stmt->getOutputMetadata(&db.status);
			std::vector<unsigned char> buf(out->getMessageLength(&db.status));
			stmt->execute(&db.status, tra, nullptr, nullptr, out, buf.data());
			ISC_LONG newId;
			memcpy(&newId, buf.data() + out->getOffset(&db.status, 0), sizeof newId);
			printf("%-42s -> NEW_ID = %d\n", call, newId);
			out->release();
			stmt->free(&db.status);
		}

		// -- 2. The trigger fired once per insert. -------------------------
		printf("audit_log rows (trigger emp_bi):              %s\n",
			db.queryValue(tra, "SELECT COUNT(*) FROM audit_log").c_str());

		// -- 3. Selectable procedure: SUSPEND streams rows into a cursor. --
		printf("\nSELECT * FROM raises(10):\n");
		fbsample::Db::print(db.query(tra,
			"SELECT id, name, new_salary FROM raises(10) ORDER BY id"));

		// -- 4. The custom exception, with its PSQL stack trace.  (Use the
		// prepared path: on this server, execute-immediate with no output
		// metadata swallows a PSQL exception from EXECUTE PROCEDURE.) ------
		printf("\nEXECUTE PROCEDURE hire('Poorpay', 500) ->\n");
		try
		{
			IStatement* stmt = db.att->prepare(&db.status, tra, 0,
				"EXECUTE PROCEDURE hire('Poorpay', 500)", SQL_DIALECT_V6,
				IStatement::PREPARE_PREFETCH_METADATA);
			IMessageMetadata* out = stmt->getOutputMetadata(&db.status);
			std::vector<unsigned char> buf(out->getMessageLength(&db.status));
			stmt->execute(&db.status, tra, nullptr, nullptr, out, buf.data());
		}
		catch (const FbException& e)
		{
			char buf[1024];
			master->getUtilInterface()->formatStatus(buf, sizeof buf, e.getStatus());
			printf("%s\n", buf);
			db.status.init();
		}

		tra->commit(&db.status);
		printf("done.\n");
	}
	catch (const FbException& error)
	{
		return fbsample::report(error);
	}
	return 0;
}
