//
// Psql.cs - every PSQL module type driven from the client (C# twin of
// ../../cpp/psql.cpp; see ../../../psql-and-stored-procedures.md).
//
// The document's worked examples on a scratch database: an executable
// procedure (hire) with INSERT ... RETURNING into an output parameter, a
// BEFORE INSERT trigger writing an audit row, a selectable procedure
// (raises) streaming SUSPENDed rows, and a custom exception with its PSQL
// stack trace.
//
// ADO.NET has a call verb too - CommandType.StoredProcedure with the bare
// procedure name as CommandText - but where Jaybird picks EXECUTE PROCEDURE
// or SELECT * FROM from the catalog (RDB$PROCEDURE_TYPE), FirebirdClient
// picks it from the *method* you call: ExecuteNonQuery / ExecuteScalar
// build EXECUTE PROCEDURE and fill ParameterDirection.Output parameters
// from the single output message; ExecuteReader builds SELECT * FROM
// proc(...) and opens a cursor.  So the executable/selectable divide is
// the caller's to respect - the sample also calls the selectable procedure
// the executable way, and gets only the values of its first SUSPEND.
//
// Run:  cd samples/csharp && dotnet run -- Psql [database]
//
using System.Data;
using FirebirdSql.Data.FirebirdClient;
using static FbSamples.FbSample;

namespace FbSamples.Samples;

public static class Psql
{
    static FbCommand Hire(FbConnection con, string name, int salary)
    {
        var cmd = new FbCommand("hire", con) { CommandType = CommandType.StoredProcedure };
        cmd.Parameters.AddWithValue("p_name", name);
        cmd.Parameters.AddWithValue("p_salary", salary);
        cmd.Parameters.Add(new FbParameter("new_id", FbDbType.Integer) { Direction = ParameterDirection.Output });
        return cmd;
    }

    public static void Run(string[] args)
    {
        using var con = AttachOrCreate(DbPath("psql", args));

        // -- Schema (auto-commit), idempotent: stub the procedures first so
        //    RECREATE TABLE emp is not blocked by their dependencies.
        Execute(con, "create or alter procedure hire (p_name varchar(30),"
                     + " p_salary numeric(10,2)) returns (new_id integer) as begin end");
        Execute(con, "create or alter procedure raises (pct numeric(5,2))"
                     + " returns (id integer, name varchar(30), new_salary numeric(10,2))"
                     + " as begin end");
        Execute(con, "recreate table emp (id int generated by default as"
                     + " identity primary key, name varchar(30), salary numeric(10,2))");
        Execute(con, "recreate table audit_log (logged_at timestamp, what varchar(60))");
        Execute(con, "create or alter exception low_salary 'salary below minimum'");
        Execute(con, """
            CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))
            RETURNS (new_id INTEGER) AS
            BEGIN
              IF (p_salary < 1000) THEN EXCEPTION low_salary;
              INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)
                RETURNING id INTO :new_id;
            END
            """);
        Execute(con, """
            CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS
            BEGIN
              INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,
                'insert emp ' || COALESCE(NEW.name, '?'));
            END
            """);
        Execute(con, """
            CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))
            RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS
            BEGIN
              FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO
              BEGIN
                new_salary = new_salary * (1 + pct / 100);
                SUSPEND;
              END
            END
            """);

        // -- 1. Executable procedure: one output message, no cursor --------------
        foreach (var (name, salary) in new[] { ("Ada", 5000), ("Grace", 6000) })
        {
            using var cmd = Hire(con, name, salary);
            cmd.ExecuteNonQuery();                               // EXECUTE PROCEDURE hire ...
            Console.WriteLine($"{$"ExecuteNonQuery hire('{name}', {salary})",-42} -> NEW_ID = {cmd.Parameters["new_id"].Value}");
        }

        // -- 2. The trigger fired once per insert --------------------------------
        Console.WriteLine($"audit_log rows (trigger emp_bi):              {Scalar(con, "select count(*) from audit_log")}");

        // -- 3. Selectable procedure: ExecuteReader opens a cursor ---------------
        Console.WriteLine();
        Console.WriteLine("ExecuteReader raises(10):");
        using (var cmd = new FbCommand("raises", con) { CommandType = CommandType.StoredProcedure })
        {
            cmd.Parameters.AddWithValue("pct", 10);
            using var r = cmd.ExecuteReader();                   // SELECT * FROM raises(...)
            Console.WriteLine("ID NAME  NEW_SALARY");
            Console.WriteLine("-- ----- ----------");
            while (r.Read())
                Console.WriteLine($"{r.GetInt32(0),-2} {r.GetString(1),-5} {r.GetDecimal(2):F2}  ({r.GetValue(2).GetType().Name})");
        }

        // -- 3b. ... and the same procedure through the executable verb ----------
        using (var cmd = new FbCommand("raises", con) { CommandType = CommandType.StoredProcedure })
        {
            cmd.Parameters.AddWithValue("pct", 10);
            foreach (var (p, t) in new[] { ("id", FbDbType.Integer), ("name", FbDbType.VarChar), ("new_salary", FbDbType.Numeric) })
                cmd.Parameters.Add(new FbParameter(p, t) { Direction = ParameterDirection.Output });
            cmd.ExecuteNonQuery();                               // EXECUTE PROCEDURE raises ...
            Console.WriteLine($"ExecuteNonQuery raises(10)                 -> ID = {cmd.Parameters["id"].Value}, "
                              + $"NAME = {cmd.Parameters["name"].Value}, NEW_SALARY = {cmd.Parameters["new_salary"].Value}"
                              + "   (first SUSPEND only)");
        }

        // -- 4. The custom exception, with its PSQL stack trace ------------------
        Console.WriteLine();
        Console.WriteLine("ExecuteNonQuery hire('Poorpay', 500) ->");
        try
        {
            using var cmd = Hire(con, "Poorpay", 500);
            cmd.ExecuteNonQuery();
            Console.WriteLine("unexpected: hire succeeded");
        }
        catch (FbException e)
        {
            Console.WriteLine(ErrorText(e));
            var codes = string.Join(", ", e.Errors.Select(x => x.Number).Where(n => n != 0).Distinct());
            Console.WriteLine($"(SQLSTATE {e.SQLSTATE}, gds [{codes}])");
        }
        Console.WriteLine("done.");
    }
}
