#
# psql.py - every PSQL module type driven from the client (Python twin of
# ../cpp/psql.cpp; see ../../psql-and-stored-procedures.md).
#
#   - an executable procedure (hire) with INSERT ... RETURNING into an output
#     parameter: one output message, no cursor;
#   - a BEFORE INSERT trigger writing an audit row per hire;
#   - a selectable procedure (raises) streaming SUSPENDed rows, fetched like
#     a table with SELECT ... FROM raises(10);
#   - a custom PSQL exception, caught client-side with its PSQL stack trace.
#
# firebird-driver names the executable/selectable divide twice: the prepared
# Statement's .type is StatementType.EXEC_PROCEDURE vs SELECT, and the
# Cursor offers call_procedure() - EXECUTE PROCEDURE returning the single
# output message as a tuple - next to execute()+fetch for the SUSPEND stream.
# NUMERIC(10,2) stays exact as decimal.Decimal.  Idempotent - safe to re-run.
#
# Run:  python3 psql.py [database]
#
from decimal import Decimal

from firebird.driver import DatabaseError

from fbsample import attach_or_create, db_path, error_text, execute, query, run, scalar


def main():
    with attach_or_create(db_path('psql')) as db:
        # -- Schema: the document's worked examples, made idempotent. -------
        # On re-runs the procedures still reference emp; reduce them to stubs
        # first so RECREATE TABLE is not blocked by dependencies.
        execute(db, 'CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30),'
                    ' p_salary NUMERIC(10,2)) RETURNS (new_id INTEGER) AS BEGIN END')
        execute(db, 'CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))'
                    ' RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))'
                    ' AS BEGIN END')
        execute(db, 'RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS'
                    ' IDENTITY PRIMARY KEY, name VARCHAR(30), salary NUMERIC(10,2))')
        execute(db, 'RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))')
        execute(db, "CREATE OR ALTER EXCEPTION low_salary 'salary below minimum'")
        execute(db, '''CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))
RETURNS (new_id INTEGER) AS
BEGIN
  IF (p_salary < 1000) THEN EXCEPTION low_salary;
  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)
    RETURNING id INTO :new_id;
END''')
        execute(db, '''CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS
BEGIN
  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,
    'insert emp ' || COALESCE(NEW.name, '?'));
END''')
        execute(db, '''CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))
RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS
BEGIN
  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO
  BEGIN
    new_salary = new_salary * (1 + pct / 100);
    SUSPEND;
  END
END''')

        cur = db.cursor()

        # -- 1. Executable procedure: one output message, no cursor. --------
        for name, salary in (('Ada', 5000), ('Grace', 6000)):
            out = cur.call_procedure('hire', [name, Decimal(salary)])
            print(f"{f'call_procedure(hire, {name!r}, {salary})':<42} -> NEW_ID = {out[0]}")

        # -- 2. The trigger fired once per insert. --------------------------
        print('audit_log rows (trigger emp_bi):             ',
              scalar(db, 'SELECT COUNT(*) FROM audit_log'))

        # -- 3. Selectable procedure: SUSPEND streams rows into a cursor. ---
        for sql in ('EXECUTE PROCEDURE hire(?, ?)', 'SELECT * FROM raises(?)'):
            with cur.prepare(sql) as stmt:
                print(f'cur.prepare({sql!r}).type = {stmt.type.name}')
        print('\nSELECT * FROM raises(10):')
        for row in query(db, 'SELECT id, name, new_salary FROM raises(10) ORDER BY id'):
            print('  ', row)

        # -- 4. The custom exception, with its PSQL stack trace. ------------
        print("\ncall_procedure(hire, 'Poorpay', 500) ->")
        try:
            cur.call_procedure('hire', ['Poorpay', Decimal(500)])
        except DatabaseError as e:
            print(error_text(e))
            print(f'(sqlcode {e.sqlcode}, gds {e.gds_codes[0]})')
        cur.close()
        db.commit()
    print('done.')


if __name__ == '__main__':
    run(main)
