// psql - one of each PSQL module type, driven from the client (Go twin of
// ../../cpp/psql.cpp; see ../../../psql-and-stored-procedures.md).
//
// An executable procedure (hire, INSERT ... RETURNING into an output
// parameter), a BEFORE INSERT trigger writing an audit row, a selectable
// procedure (raises) streaming SUSPENDed rows, and a custom exception
// caught client-side with its PSQL stack trace.  Idempotent.
//
// database/sql has no "call" verb - only Exec and Query - so the
// executable-vs-selectable divide lives inside the driver: when the prepare
// reports isc_info_sql_stmt_exec_procedure, firebirdsql sends op_execute2,
// reads the ONE output message from op_sql_response, and dresses it up as a
// one-row *sql.Rows; a selectable procedure goes through op_execute + a
// real cursor (op_fetch) like any table.  Same QueryRow/Query on the Go
// side, two different wire conversations underneath.  NUMERIC(10,2) arrives
// as an exact decimal string, and the exception is a *firebirdsql.FbError
// with the whole status vector.
//
// Run:  go run ./psql [database]
package main

import (
	"fmt"

	"github.com/mariuz/conceptual-architecture-for-firebird-paper/samples/go/fbsample"
)

func main() {
	db, err := fbsample.Create(fbsample.DBPath("psql"))
	fbsample.Check(err)
	defer db.Close()

	// -- Schema: the document's worked examples, made idempotent. ----------
	// On re-runs the procedures still reference emp; reduce them to stubs
	// first so RECREATE TABLE is not blocked by their dependencies.
	for _, q := range []string{
		"CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30)," +
			" p_salary NUMERIC(10,2)) RETURNS (new_id INTEGER) AS BEGIN END",
		"CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))" +
			" RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))" +
			" AS BEGIN END",
		"RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS" +
			" IDENTITY PRIMARY KEY, name VARCHAR(30), salary NUMERIC(10,2))",
		"RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))",
		"CREATE OR ALTER EXCEPTION low_salary 'salary below minimum'",
		`CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))
RETURNS (new_id INTEGER) AS
BEGIN
  IF (p_salary < 1000) THEN EXCEPTION low_salary;
  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)
    RETURNING id INTO :new_id;
END`,
		`CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS
BEGIN
  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,
    'insert emp ' || COALESCE(NEW.name, '?'));
END`,
		`CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))
RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS
BEGIN
  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO
  BEGIN
    new_salary = new_salary * (1 + pct / 100);
    SUSPEND;
  END
END`,
	} {
		_, err := db.Exec(q)
		fbsample.Check(err)
	}

	tx, err := db.Begin()
	fbsample.Check(err)
	defer tx.Rollback()

	// -- 1. Executable procedure: one output message, no cursor. -----------
	for _, hire := range []struct {
		name   string
		salary int
	}{{"Ada", 5000}, {"Grace", 6000}} {
		var newID int64
		fbsample.Check(tx.QueryRow("EXECUTE PROCEDURE hire(?, ?)", hire.name, hire.salary).Scan(&newID))
		fmt.Printf("%-42s -> NEW_ID = %d\n",
			fmt.Sprintf("EXECUTE PROCEDURE hire('%s', %d)", hire.name, hire.salary), newID)
	}

	// -- 2. The trigger fired once per insert. -----------------------------
	n, err := fbsample.Scalar(tx, "SELECT COUNT(*) FROM audit_log")
	fbsample.Check(err)
	fmt.Printf("audit_log rows (trigger emp_bi):              %v\n", n)

	// -- 3. Selectable procedure: SUSPEND streams rows into a cursor. ------
	fmt.Println("\nSELECT * FROM raises(10):")
	rows, err := tx.Query("SELECT id, name, new_salary FROM raises(?) ORDER BY id", 10)
	fbsample.Check(err)
	fmt.Println("ID NAME  NEW_SALARY")
	fmt.Println("-- ----- ----------")
	for rows.Next() {
		var id int64
		var name, salary string // NUMERIC(10,2): an exact decimal string
		fbsample.Check(rows.Scan(&id, &name, &salary))
		fmt.Printf("%-2d %-5s %s\n", id, name, salary)
	}
	fbsample.Check(rows.Err())
	rows.Close()

	// -- 4. The custom exception, with its PSQL stack trace. ---------------
	fmt.Println("\nEXECUTE PROCEDURE hire('Poorpay', 500) ->")
	var newID int64
	err = tx.QueryRow("EXECUTE PROCEDURE hire(?, ?)", "Poorpay", 500).Scan(&newID)
	if err == nil {
		fmt.Println("BUG: no exception, NEW_ID =", newID)
	} else {
		fmt.Println(fbsample.ErrText(err))
		if fe, ok := fbsample.FbError(err); ok {
			fmt.Printf("(sqlcode %d, sqlstate %s, gds %v)\n", fe.SQLCode, fe.SQLState, fe.GDSCodes)
		}
	}
	fbsample.Check(tx.Commit())
	fmt.Println("done.")
}
