//
// Psql.java - every PSQL module type driven from the client (Java twin of
// ../../../../../cpp/psql.cpp; see
// ../../../../../../psql-and-stored-procedures.md).
//
// The document's worked examples on a scratch database: an executable
// procedure (hire) with INSERT ... RETURNING into an output parameter, a
// BEFORE INSERT trigger writing an audit row, a selectable procedure
// (raises) streaming SUSPENDed rows, and a custom exception with its PSQL
// stack trace.
//
// JDBC is the one API among the twins with a *call* verb of its own:
// CallableStatement and the {call proc(?, ...)} escape.  Jaybird resolves
// the escape against the catalog - RDB$PROCEDURE_TYPE says whether the
// procedure is executable or selectable (FirebirdCallableStatement.
// isSelectableProcedure()) - and sends EXECUTE PROCEDURE for hire, whose
// single output message it keeps as a one-row "singleton" result read
// through the registered OUT parameter, but SELECT * FROM raises(?) for
// the selectable one, whose SUSPENDed rows come back as a real cursor
// ResultSet.  Same verb, two statements.
// NUMERIC(10,2) stays exact as BigDecimal, and the exception's status
// vector arrives both as text and as a cause chain of gds codes.
//
// Run:  cd samples/java && mvn -q compile exec:exec -Dsample=Psql
//
package fbsamples;

import static fbsamples.FbSample.attachOrCreate;
import static fbsamples.FbSample.dbPath;
import static fbsamples.FbSample.execute;
import static fbsamples.FbSample.scalar;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

import org.firebirdsql.jdbc.FirebirdCallableStatement;

public final class Psql {

    private static void hire(Connection con, String name, int salary) throws SQLException {
        try (CallableStatement cs = con.prepareCall("{call hire(?, ?, ?)}")) {
            cs.setString(1, name);
            cs.setInt(2, salary);
            cs.registerOutParameter(3, Types.INTEGER);
            cs.execute();
            System.out.printf("%-42s -> NEW_ID = %d   (selectable: %b)%n",
                    "{call hire('" + name + "', " + salary + ")}", cs.getInt(3),
                    cs.unwrap(FirebirdCallableStatement.class).isSelectableProcedure());
        }
    }

    public static void main(String[] args) {
        FbSample.run(() -> {
            String path = dbPath("psql", args);
            try (Connection con = attachOrCreate(path)) {
                // -- Schema (auto-commit), idempotent: stub the procedures first so
                //    RECREATE TABLE emp is not blocked by their dependencies.
                execute(con, "create or alter procedure hire (p_name varchar(30),"
                        + " p_salary numeric(10,2)) returns (new_id integer) as begin end");
                execute(con, "create or alter procedure raises (pct numeric(5,2))"
                        + " returns (id integer, name varchar(30), new_salary numeric(10,2))"
                        + " as begin end");
                execute(con, "recreate table emp (id int generated by default as"
                        + " identity primary key, name varchar(30), salary numeric(10,2))");
                execute(con, "recreate table audit_log (logged_at timestamp, what varchar(60))");
                execute(con, "create or alter exception low_salary 'salary below minimum'");
                execute(con, """
                        CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))
                        RETURNS (new_id INTEGER) AS
                        BEGIN
                          IF (p_salary < 1000) THEN EXCEPTION low_salary;
                          INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)
                            RETURNING id INTO :new_id;
                        END""");
                execute(con, """
                        CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS
                        BEGIN
                          INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,
                            'insert emp ' || COALESCE(NEW.name, '?'));
                        END""");
                execute(con, """
                        CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))
                        RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS
                        BEGIN
                          FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO
                          BEGIN
                            new_salary = new_salary * (1 + pct / 100);
                            SUSPEND;
                          END
                        END""");

                // -- 1. Executable procedure: one output message, no cursor --------
                hire(con, "Ada", 5000);
                hire(con, "Grace", 6000);

                // -- 2. The trigger fired once per insert --------------------------
                System.out.println("audit_log rows (trigger emp_bi):              "
                        + scalar(con, "select count(*) from audit_log"));

                // -- 3. Selectable procedure: the same verb yields a ResultSet -----
                System.out.println();
                System.out.println("{call raises(10)}:");
                try (CallableStatement cs = con.prepareCall("{call raises(?)}")) {
                    cs.setInt(1, 10);
                    System.out.println("(selectable: "
                            + cs.unwrap(FirebirdCallableStatement.class).isSelectableProcedure() + ")");
                    try (ResultSet rs = cs.executeQuery()) {
                        System.out.println("ID NAME  NEW_SALARY");
                        System.out.println("-- ----- ----------");
                        while (rs.next()) {
                            System.out.printf("%-2d %-5s %s  (%s)%n", rs.getInt(1), rs.getString(2),
                                    rs.getBigDecimal(3), rs.getObject(3).getClass().getSimpleName());
                        }
                    }
                }

                // -- 4. The custom exception, with its PSQL stack trace ------------
                System.out.println();
                System.out.println("{call hire('Poorpay', 500)} ->");
                try (CallableStatement cs = con.prepareCall("{call hire(?, ?, ?)}")) {
                    cs.setString(1, "Poorpay");
                    cs.setInt(2, 500);
                    cs.registerOutParameter(3, Types.INTEGER);
                    cs.execute();
                    System.out.println("unexpected: hire succeeded");
                } catch (SQLException e) {
                    String m = e.getMessage();
                    int br = m.lastIndexOf(" [SQLState:");
                    System.out.println((br >= 0 ? m.substring(0, br) : m).replace("; ", "\n"));
                    List<Integer> codes = new ArrayList<>();
                    if (e.getCause() instanceof SQLException info) {
                        for (SQLException s = info; s != null; s = s.getNextException()) {
                            codes.add(s.getErrorCode());
                        }
                    }
                    System.out.println("(SQLState " + e.getSQLState() + ", gds " + codes + ")");
                }
            }
            System.out.println("done.");
        });
    }
}
