//
// psql.js — companion to ../../psql-and-stored-procedures.md
//
// The JavaScript twin of ../cpp/psql.cpp: creates (idempotently) and calls
// the same PSQL objects through node-firebird.  EXECUTE PROCEDURE returns
// its single output row like a query; the selectable procedure is simply
// SELECTed from; and the custom exception arrives as a JS Error whose
// message is the same status vector the C++ sample formats — including the
// "At procedure ... line: N, col: M" PSQL stack trace.
//
'use strict';

const { attachOrCreate, s } = require('./common');

const DB = process.env.FB_DATABASE || '/tmp/fbhandson/psql.fdb';

const SETUP = [
    // Stubs first, so RECREATE TABLE is not blocked by dependencies on re-runs.
    'CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))'
        + ' RETURNS (new_id INTEGER) AS BEGIN END',
    'CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))'
        + ' RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))'
        + ' AS BEGIN END',
    'RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        + ' name VARCHAR(30), salary NUMERIC(10,2))',
    'RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))',
    "CREATE OR ALTER EXCEPTION low_salary 'salary below minimum'",
    'CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))\n'
        + 'RETURNS (new_id INTEGER) AS\nBEGIN\n'
        + '  IF (p_salary < 1000) THEN EXCEPTION low_salary;\n'
        + '  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)\n'
        + '    RETURNING id INTO :new_id;\nEND',
    'CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS\nBEGIN\n'
        + "  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,\n"
        + "    'insert emp ' || COALESCE(NEW.name, '?'));\nEND",
    'CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))\n'
        + 'RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS\nBEGIN\n'
        + '  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO\n'
        + '  BEGIN\n'
        + '    new_salary = new_salary * (1 + pct / 100);\n'
        + '    SUSPEND;\n'
        + '  END\nEND',
];

(async () => {
    const conn = await attachOrCreate({ database: DB, encoding: 'UTF8' });
    try {
        for (const ddl of SETUP) await conn.query(ddl);

        // 1. Executable procedure: the single output row comes back as a
        // plain object (not an array — there is no cursor to fetch from).
        for (const [name, sal] of [['Ada', 5000], ['Grace', 6000]]) {
            const r = await conn.query('EXECUTE PROCEDURE hire(?, ?)', [name, sal]);
            console.log(`hire('${name}', ${sal})  ->  NEW_ID = ${r.NEW_ID}`);
        }

        // 2. The BEFORE INSERT trigger fired per row.
        const audit = await conn.query('SELECT COUNT(*) AS c FROM audit_log');
        console.log('audit_log rows (trigger emp_bi):', Number(audit[0].C));

        // 3. Selectable procedure: SUSPEND rows fetched like a table.
        console.log('\nSELECT * FROM raises(10):');
        for (const r of await conn.query(
                'SELECT id, name, new_salary FROM raises(10) ORDER BY id'))
            console.log(`  ${r.ID}  ${s(r.NAME).padEnd(6)} ${r.NEW_SALARY.toFixed(2)}`);

        // 4. The custom exception, PSQL stack trace included.
        console.log("\nEXECUTE PROCEDURE hire('Poorpay', 500) ->");
        try {
            await conn.query('EXECUTE PROCEDURE hire(?, ?)', ['Poorpay', 500]);
        } catch (err) {
            console.log('  ' + err.message.trim().replace(/\n/g, '\n  '));
        }
    } finally {
        await conn.detach();
    }
})().catch(e => { console.error(e.message || e); process.exit(1); });
