/*
 *  psql.cpp (fb-cpp) — every PSQL module type, through typed statements.
 *
 *  The fb-cpp twin of ../cpp/psql.cpp: the same worked examples — an
 *  executable procedure (hire), a BEFORE INSERT trigger (emp_bi), a
 *  selectable procedure (raises), a custom exception — with the language
 *  distinctions surfacing as fb-cpp types.  Statement::getType() returns
 *  StatementType::EXEC_PROCEDURE for EXECUTE PROCEDURE (one output message,
 *  no cursor: execute() fills it, the typed getters read it) and
 *  StatementType::SELECT for the SUSPEND-streaming raises(10) (execute()
 *  opens the cursor and fetches the first row, fetchNext() the rest).
 *  Output values arrive as std::optional; NUMERIC(10,2) prints itself with
 *  its scale through getString().  The failing hire throws a typed
 *  DatabaseException whose what() carries the PSQL stack trace.
 *  See ../../psql-and-stored-procedures.md.
 *
 *  Uses its own scratch database — idempotent, safe to re-run.
 *
 *  Build & run (see ../README.md):
 *      ./build/fbcpp_psql [database]
 */

#include "fbcpp_sample.h"
#include <cstdio>

using namespace fbcpp;
using namespace fbcpp_sample;

static void exec(Attachment& att, Transaction& tra, const char* sql)
{
	Statement{att, tra, sql}.execute(tra);
}

int main(int argc, char** argv)
{
	const char* database = argOrDefault(argc, argv, 1,
		"inet://localhost//tmp/fbhandson/psql_fbcpp.fdb");

	try
	{
		Client client{"fbclient"};
		Attachment att = attachOrCreate(client, database);
		Transaction tra{att};

		// -- Schema: the document's worked examples, made idempotent. ------
		// On re-runs the procedures still reference emp; reduce them to
		// stubs first so RECREATE TABLE is not blocked by dependencies.
		exec(att, tra, "CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30),"
			" p_salary NUMERIC(10,2)) RETURNS (new_id INTEGER) AS BEGIN END");
		exec(att, tra, "CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))"
			" RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2))"
			" AS BEGIN END");
		tra.commitRetaining();
		exec(att, tra, "RECREATE TABLE emp (id INT GENERATED BY DEFAULT AS"
			" IDENTITY PRIMARY KEY, name VARCHAR(30), salary NUMERIC(10,2))");
		exec(att, tra, "RECREATE TABLE audit_log (logged_at TIMESTAMP, what VARCHAR(60))");
		exec(att, tra, "CREATE OR ALTER EXCEPTION low_salary 'salary below minimum'");
		tra.commitRetaining();

		exec(att, tra,
			"CREATE OR ALTER PROCEDURE hire (p_name VARCHAR(30), p_salary NUMERIC(10,2))\n"
			"RETURNS (new_id INTEGER) AS\n"
			"BEGIN\n"
			"  IF (p_salary < 1000) THEN EXCEPTION low_salary;\n"
			"  INSERT INTO emp (name, salary) VALUES (:p_name, :p_salary)\n"
			"    RETURNING id INTO :new_id;\n"
			"END");
		exec(att, tra,
			"CREATE OR ALTER TRIGGER emp_bi BEFORE INSERT ON emp AS\n"
			"BEGIN\n"
			"  INSERT INTO audit_log VALUES (CURRENT_TIMESTAMP,\n"
			"    'insert emp ' || COALESCE(NEW.name, '?'));\n"
			"END");
		exec(att, tra,
			"CREATE OR ALTER PROCEDURE raises (pct NUMERIC(5,2))\n"
			"RETURNS (id INTEGER, name VARCHAR(30), new_salary NUMERIC(10,2)) AS\n"
			"BEGIN\n"
			"  FOR SELECT id, name, salary FROM emp INTO :id, :name, :new_salary DO\n"
			"  BEGIN\n"
			"    new_salary = new_salary * (1 + pct / 100);\n"
			"    SUSPEND;\n"                       // yield one row to the caller
			"  END\n"
			"END");
		tra.commitRetaining();

		// -- 1. Executable procedure: one output message, no cursor. -------
		for (const char* call : { "EXECUTE PROCEDURE hire('Ada', 5000)",
		                          "EXECUTE PROCEDURE hire('Grace', 6000)" })
		{
			Statement stmt{att, tra, call};
			stmt.execute(tra);
			printf("%-42s -> NEW_ID = %d   [%s]\n", call,
				stmt.getInt32(0).value_or(-1),
				stmt.getType() == StatementType::EXEC_PROCEDURE
					? "type=EXEC_PROCEDURE" : "type=?");
		}

		// -- 2. The trigger fired once per insert. -------------------------
		Statement audits{att, tra, "SELECT COUNT(*) FROM audit_log"};
		audits.execute(tra);
		printf("audit_log rows (trigger emp_bi):              %ld\n",
			static_cast<long>(audits.getInt64(0).value_or(0)));

		// -- 3. Selectable procedure: SUSPEND streams rows into a cursor. --
		printf("\nSELECT * FROM raises(10):\n");
		Statement sel{att, tra,
			"SELECT id, name, new_salary FROM raises(10) ORDER BY id"};
		for (bool more = sel.execute(tra); more; more = sel.fetchNext())
			printf("%-2d %-5s %s\n",
				sel.getInt32(0).value_or(-1),
				sel.getString(1).value_or("?").c_str(),
				sel.getString(2).value_or("?").c_str());

		// -- 4. The custom exception, with its PSQL stack trace. -----------
		printf("\nEXECUTE PROCEDURE hire('Poorpay', 500) ->\n");
		try
		{
			Statement stmt{att, tra, "EXECUTE PROCEDURE hire('Poorpay', 500)"};
			stmt.execute(tra);
		}
		catch (const DatabaseException& e)
		{
			printf("(gds %ld = isc_except)\n%s\n",
				static_cast<long>(e.getErrorCode()), e.what());
		}

		tra.commit();
		printf("done.\n");
		return 0;
	}
	catch (const std::exception& e)
	{
		return report(e);
	}
}
